config/routes.rb
Ticketing::Application.routes.draw do
  resources :tickets
  resources :users
  
  match "/auth/github/callback" => "sessions#create"
  match "/logout" => "sessions#destroy"

  root :to => "tickets#index"

end

app/models/bug.rb
class Bug < Ticket
  
  belongs_to :task
  
  state_machine do
    after_transition :on => :start_dev, :do => :start_dev_hook
  end
  
  private
  def start_dev_hook
    puts "dev started"
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :ticket
  belongs_to :user
end

app/models/feature.rb
class Feature < Ticket
  has_many :tasks
  has_many :bugs
end

app/models/select_fixed_in_version.rb
class SelectFixedInVersion < ActiveRecord::Base
end

app/models/task.rb
class Task < Ticket
  belongs_to :feature
  has_many :bugs
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  
  has_many :comments
  
  state_machine :initial => :open do
    
    before_transition :on => :start_dev, :do => :say_hello
    
    event :start_dev do      
      transition [:open, :failed_test, :failed_retest_on_trunk, :paused, :reopened, :invalid] => :in_dev
    end
    
    event :make_invalid do
      transition [:open, :paused] => :invalid
    end
    
    event :pause_dev do
      transition :in_dev => :paused
    end
    
    event :finish_dev do
      transition :in_dev => :in_test
    end
    
    event :retest_on_trunk do
      transition :in_test => :retest_on_trunk
    end
    
    event :fail_test do
      transition :in_test => :failed_test
      transition :retest_on_trunk => :failed_retest_on_trunk
    end
    
    event :pass_test do
      transition [:in_test, :retest_on_trunk] => :closed
    end
    
    event :reopen do
      transition :closed => :reopened
    end
    
  end
        
  def say_hello
    puts "hello"
  end
end

app/models/user.rb
class User < ActiveRecord::Base  
  def self.create_with_omniauth(auth)  
    user = find_by_nickname(auth["user_info"]["nickname"]) || return
    user.provider = auth["provider"]  
    user.uid = auth["uid"]  
    user.name = auth["user_info"]["name"]
    user.save
    return user
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user  
  
  private  
  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["uid"]) || User.create_with_omniauth(auth)
    unless user.nil?
      session[:user_id] = user.id  
      flash[:notice] = "Greetings, #{auth["user_info"]["name"]}!"
    else
      flash[:error] = "To be able to log in, your GitHub username, #{auth["user_info"]["nickname"]}, needs to be registered in Tackle by an administrator."
    end
    redirect_to root_url 
  end
  
  def destroy  
    session[:user_id] = nil  
    redirect_to root_url, :notice => "Signed out!"  
  end  
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.order("id desc").page(params[:page]).per(30)
    
    respond_to do |format|
      format.html
    end
  end  
  
  def create
    @ticket = Ticket.new(params[:ticket])
    @ticket.type = params[:type]
    respond_to do |format|
      if @ticket.save
          format.html { redirect_to(tickets_path,
                      :notice => "#{@ticket.type} was successfully created.") }
        else
          format.html { redirect_to(new_ticket_path(:type => @ticket.type)) }
        end
    end
  end
  
  def edit
    @ticket = Ticket.find_by_id(params[:id])
  end
  
  def update
    @ticket = Ticket.find_by_id(params[:id])
    respond_to do |format|
      if ticket_is_successfully_updated
        @ticket.send(params[:event][:fire])
        format.html { redirect_to(tickets_path,
                      :notice => "#{@ticket.type} was successfully updated.") }
      else
        format.html { render :action => "edit" }
      end
    end
  end
  
  private
  def ticket_is_successfully_updated
    @ticket.state_events.include?(params[:event][:fire].to_sym) && @ticket.update_attributes(params[@ticket.type.downcase])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.order("nickname").page(params[:page]).per(30)
    respond_to do |format|
      format.html
    end
  end  
  
  def create
    @user = User.new(params[:user])
    respond_to do |format|
      if @user.save
          format.html { redirect_to(users_path,
                      :notice => "User was successfully created.") }
        else
          format.html { redirect_to(new_user_path) }
        end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/bugs/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "List", tickets_path  %></li>
      <li><%= link_to "New Story", new_story_path %></li>
      <li><%= link_to "New Task", new_task_path %></li>
      <li><%= link_to "New Bug", new_bug_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">Edit Bug</h2>
    <div class="inner">
    <%= form_for @bug, :html => { :class => :form } do |f| -%>
        <%= render :partial => "tickets/form", :locals => {:f => f} %>
      <% end -%>  
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'tickets/sidebar') -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tackle</title>
  <%= stylesheet_link_tag "web-app-theme/base", "web-app-theme/themes/drastic-dark/style", "web-app-theme/override"%>
  <%= javascript_include_tag :defaults%>
  <%= csrf_meta_tag %>
<!-- Start Visual Website Optimizer Code -->
<script type='text/javascript'>
var _vis_opt_account_id = 9492;
var _vis_opt_protocol = (('https:' == document.location.protocol) ? 'https://' : 'http://');
document.write('<s' + 'cript src="' + _vis_opt_protocol + 'dev.visualwebsiteoptimizer.com/deploy/js_visitor_settings.php?v=1&a='+_vis_opt_account_id+'&url='+encodeURIComponent(document.URL)+'&random='+Math.random()+'" type="text/javascript">' + '<\/s' + 'cript>');
</script>
<script type='text/javascript'>
if(typeof(_vis_opt_settings_loaded) == "boolean") { document.write('<s' + 'cript src="' + _vis_opt_protocol + 'd5phz18u4wuww.cloudfront.net/vis_opt.js" type="text/javascript">' + '<\/s' + 'cript>'); }
// if your site already has jQuery 1.4.2, replace vis_opt.js with vis_opt_no_jquery.js above
</script>
<script type='text/javascript'>
if(typeof(_vis_opt_settings_loaded) == "boolean" && typeof(_vis_opt_top_initialize) == "function"){ _vis_opt_top_initialize();
vwo_$(document).ready(function() { _vis_opt_bottom_initialize(); }); }
</script>
<!-- End Visual Website Optimizer Code -->
</head>
<body>
  <div id="container">
    <div id="header">
      <h1><a href="#">Tackle</a></h1>
        <% if current_user %>
        <div id="title-right">Logged in as <%= current_user.name %></div>
        <% end %>
      <div id="user-navigation">
        <ul class="wat-cf">
          <li><a href="#">Profile</a></li>
          <li><a href="#">Settings</a></li>
          <li><% if current_user %>
            <a href="/logout" class="logout">Logout</a>
          <% else %>
            <a href="/auth/github">Login</a>
          <% end %>
          </li>
        </ul>
      </div>
      <div id="main-navigation">
        <ul class="wat-cf">
          <li class="first<%= ' active' if params[:controller] == 'tickets' %>"><%= link_to "Tickets", tickets_path  %></li>
          <li><a href="#">Sprint</a></li>
          <li<%= ' class=active' if params[:controller] == 'users' %>><%= link_to "Users", users_path  %></li>
        </ul>
      </div>
    </div>    
    <div id="wrapper" class="wat-cf">
      <div class="flash">
        <% flash.each do |type, message| -%>
          <div class="message <%= type %>">
            <p><%= message %></p>
          </div>
        <% end -%>
      </div>
      <div id="main">
        <%= yield %>
        <div id="footer">
          <div class="block">
            <p>Copyright &copy; <%= Time.now.year %> Sage Online Ticketing.</p>
          </div>      
        </div>
      </div>
      <div id="sidebar">
        <%= yield :sidebar %>
      </div>
    </div>    
  </div>
</body>
</html>

app/views/tickets/_form.html.erb
<div class="group">
  <%= f.label :title, "Title:", :class => :label %>
  <%= f.text_field :title, :class => 'text_field' %>
  <span class="description">Ex: a simple text</span>
</div>
<div class="group">
  <%= f.label :description, "Description:", :class => :label %>
  <%= f.text_area :description, :class => 'text_area' %>
  <span class="description">Ex: a simple text</span>
</div>
<div class="columns wat-cf">
  <div class="column left"> 
    <div class="group">
      <%= f.label :fixed_in_version_id, "Fixed in Version:", :class => :label %>
      <%= f.collection_select :select_fixed_in_version_id, SelectFixedInVersion.all, :id, :value %>
    </div>    
  </div>
  <div class="column right">
  </div>
</div>

<%= render :partial => "ticket_actions", :locals => {:f => f} if @ticket %>

<div class="group navform wat-cf">
  <button class="button" type="submit">
    <%= image_tag("web-app-theme/icons/tick.png", :alt => "Save") %> <%= "Save" %>
  </button>
	<%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "Cancel") + "Cancel", tickets_path, :class => "button" %>
</div>

app/views/tickets/_sidebar.html.erb
<!--<div class="block notice">
  <h3>Simple Block</h3>
  <div class="content">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.</p>
  </div>
</div>-->
<div class="block">
  <h3>Searches</h3>
  <ul class="navigation">
    <li><a href="#">All Tickets Assigned to Me</a></li>
    <li><a href="#">All Open Bugs</a></li>
    <li><a href="#">All Bugs in QA</a></li>
    <li><a href="#">All Tasks in QA</a></li>
  </ul>
</div>

app/views/tickets/_ticket_actions.html.erb
<div class="group">
  <%= f.label :action_id, "Action:", :class => :label %>
  <div>
    <%= radio_button "event", :fire, false, :checked => true  %>
    <%= f.label :state, "Leave as \"#{t @ticket.state}\"", :class => :radio%>
  </div>
  <% @ticket.state_events.each do |event| %>
  <div>
    <%= radio_button "event", :fire, event %>
    <%= f.label :state, t(event), :class => :radio %>
  </div>
  <% end %>
</div>

app/views/tickets/edit.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "List", tickets_path  %></li>
      <li><%= link_to "New Feature", new_ticket_path(:type => "Feature") %></li>
      <li><%= link_to "New Task", new_ticket_path(:type => "Task") %></li>
      <li><%= link_to "New Bug", new_ticket_path(:type => "Bug") %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title"><%= @ticket.type %> #<%= @ticket.id %></h2>
    <div class="inner">
    <%= form_for @ticket, :url => ticket_path(:type => @ticket.type), :html => { :class => :form } do |f| -%>
        <%= render :partial => "form", :locals => {:f => f} %>
      <% end -%>  
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'tickets/sidebar') -%>

app/views/tickets/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "List", tickets_path  %></li>
      <li><%= link_to "New Feature", new_ticket_path(:type => "Feature") %></li>
      <li><%= link_to "New Task", new_ticket_path(:type => "Task") %></li>
      <li><%= link_to "New Bug", new_ticket_path(:type => "Bug") %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title">All Tickets</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">ID</th>
          <th>Title</th>
          <th>Type</th>
          <th>Status</th>
          <th class="last">Created</th>
        </tr>
        <% @tickets.each do |ticket| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= ticket.id %>
          </td>
          <td><!-- edit_ticket_path_by_type(ticket) -->
            <%= link_to ticket.title, edit_ticket_path(ticket)%>
          </td>
          <td>
            <%= ticket.type %>
          </td>
          <td>
            <%= t ticket.state%>
          </td>
          <td>
            <%= "#{time_ago_in_words ticket.created_at} ago"%>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        <%= paginate @tickets, :outer_window => 1%>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'sidebar') -%>

app/views/tickets/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "List", tickets_path  %></li>
      <li <%= params[:type] == "Feature" ? 'class=active' : '' %>><%= link_to "New Feature", new_ticket_path(:type => "Feature") %></li>
      <li <%= params[:type] == "Task" ? 'class=active' : '' %>><%= link_to "New Task", new_ticket_path(:type => "Task") %></li>
      <li <%= params[:type] == "Bug" ? 'class=active' : '' %>><%= link_to "New Bug", new_ticket_path(:type => "Bug") %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">New  <%= params[:type] %></h2>
    <div class="inner">
      <%= form_for :ticket, :url => tickets_path(:type => params[:type]), :html => { :class => :form } do |f| -%>
        <%= render :partial => "tickets/form", :locals => {:f => f} %>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'tickets/sidebar') -%>

app/views/users/index.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first active"><%= link_to "List", users_path  %></li>
      <li><%= link_to "New User", new_user_path %></li>
    </ul>
  </div>          
  <div class="content">          
    <h2 class="title">All Users</h2>
    <div class="inner">
      <table class="table">
        <tr>             
          <th class="first">Username</th>
          <th>Name</th>
          <th>Email</th>
          <th>Role</th>
          <th class="last">Created</th>
        </tr>
        <% @users.each do |user| -%>
        <tr class="<%= cycle("odd", "even") %>">
          <td>
            <%= user.nickname %>
          </td>
          <td>
            <%= user.name %>
          </td>
          <td>
            <%= user.email %>
          </td>
          <td>
            <%= user.is_admin ? 'Admin' : 'User' %>
          </td> 
          <td>
            <%= "#{time_ago_in_words user.created_at} ago"%>
          </td>
        </tr>          
        <% end -%>
      </table>
      <div class="actions-bar wat-cf">
        <div class="actions">
        </div>
        <%= paginate @users, :outer_window => 1%>
      </div>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'tickets/sidebar') -%>

app/views/users/new.html.erb
<div class="block">
  <div class="secondary-navigation">
    <ul class="wat-cf">
      <li class="first"><%= link_to "List", users_path  %></li>
      <li class="active"><%= link_to "New User", new_user_path %></li>
    </ul>
  </div>          
  <div class="content">            
    <h2 class="title">New  User</h2>
    <div class="inner">
      <%= form_for :user, :url => users_path, :html => { :class => :form } do |f| -%>
        <div class="columns wat-cf">
          <div class="column left"> 
            <div class="group">
              <%= f.label :nickname, "GitHub Username:", :class => :label %>
              <%= f.text_field :nickname, :class => 'text_field' %>
            </div>   
            <div class="group">
              <%= f.label :email, "Email:", :class => :label %>
              <%= f.text_field :email, :class => 'text_field' %>
            </div>   
          </div>
          <div class="column right">
            <div class="group">
              <%= f.label :is_admin, "Role", :class => :label %>
              <%= f.radio_button :is_admin, 'true' %> 
              <%= f.label :is_admin, 'Admin', :value => 'true', :class => :radio %>
              <%= f.radio_button :is_admin, 'false', :checked => true %>
              <%= f.label :is_admin, 'User', :value => 'false', :class => :radio %>
            </div>
          </div>
        </div>
        <div class="group navform wat-cf">
          <button class="button" type="submit">
            <%= image_tag("web-app-theme/icons/tick.png", :alt => "Save") %> <%= "Save" %>
          </button>
        	<%= link_to image_tag("web-app-theme/icons/cross.png", :alt => "Cancel") + "Cancel", users_path, :class => "button" %>
        </div>
      <% end -%>
    </div>
  </div>
</div>

<% content_for :sidebar, render(:partial => 'tickets/sidebar') -%>